server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # 账户服务路由
        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/account/**
          filters:
            - StripPrefix=2
        
        # 风控服务路由
        - id: risk-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/risk/**
          filters:
            - StripPrefix=2
        
        # 总账服务路由
        - id: ledger-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/ledger/**
          filters:
            - StripPrefix=2
        
        # 通知服务路由
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/notification/**
          filters:
            - StripPrefix=2
        
        # 转账服务路由
        - id: transfer-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/transfer/**
          filters:
            - StripPrefix=2

        # API文档路由 - 转发到account-service的Knife4j
        - id: api-docs
          uri: http://localhost:8081
          predicates:
            - Path=/doc.html

      # 全局CORS配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

